import type { PresentationConfig } from './types.ts'

export const presentationConfigV1: PresentationConfig = {
  version: 1,
  questionOrder: [1, 13, 26, 27, 30, 31, 32],
  items: {
    '1': {
      controlType: 'single_choice',
      required: true,
      groupKey: 'lifestyle',
      pageKey: 'lifestyle',
      layoutHint: 'single',
      optionKeys: ['low', 'moderate', 'elevated', 'high'],
      alwaysIncludeInSupplement: true,
    },
    '13': {
      controlType: 'number',
      required: true,
      groupKey: 'measurements',
      pageKey: 'measurements',
      layoutHint: 'pair_measurement',
      supplementMetrics: ['WAIST'],
      numericConfig: {
        unit: 'cm',
        min: 30,
        max: 250,
        step: 0.1,
        unknownOption: {
          key: 'unknown',
          label: '目前不知道',
        },
      },
    },
    '26': {
      controlType: 'single_choice',
      required: true,
      groupKey: 'measurements',
      pageKey: 'female_health',
      layoutHint: 'single',
      optionKeys: ['normal', 'heavy'],
      supplementMetrics: ['HB'],
    },
    '27': {
      controlType: 'composite_bp',
      required: true,
      groupKey: 'measurements',
      pageKey: 'measurements',
      layoutHint: 'pair_measurement',
      supplementMetrics: ['SBP', 'DBP'],
      bpConfig: {
        unit: 'mmHg',
        systolicLabel: '收縮壓',
        diastolicLabel: '舒張壓',
        unknownOption: {
          key: 'unknown',
          label: '目前不知道',
        },
      },
    },
    '30': {
      controlType: 'single_choice',
      required: true,
      groupKey: 'safety',
      pageKey: 'safety',
      layoutHint: 'pair_binary',
      optionKeys: ['no', 'yes'],
      alwaysIncludeInSupplement: true,
    },
    '31': {
      controlType: 'single_choice',
      required: true,
      groupKey: 'safety',
      pageKey: 'safety',
      layoutHint: 'pair_binary',
      optionKeys: ['no', 'yes'],
      alwaysIncludeInSupplement: true,
    },
    '32': {
      controlType: 'multi_choice',
      required: true,
      groupKey: 'safety',
      pageKey: 'allergies',
      layoutHint: 'standalone',
      optionKeys: [
        'none_known',
        'dairy',
        'soy',
        'sesame',
        'black_beans',
        'fish',
        'gluten',
        'lactose_intolerance',
        'fungi',
        'peanuts_tree_nuts',
        'other',
      ],
      exclusiveKeys: ['none_known'],
      detailInputs: {
        other: {
          required: true,
          placeholder: '請輸入過敏原名稱',
        },
      },
      alwaysIncludeInSupplement: true,
    },
  },
}
